---
name: Build and Push multi-arch Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: tag name
        type: string
        required: true
  release:
    types:
      - released
#      - published

jobs:
  build-publish-containers:
    name: Build and Publish Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
#        platform: [ linux/amd64, linux/arm64/8, windows/amd64 ]
        include:
          - platform: linux/amd64
            os: ubuntu-latest
            base: 3.15.4
            file: linux/Dockerfile
            tag-suffix: -linux-amd64
          - platform: linux/arm64/8
            os: ubuntu-latest
            base: 3.15.4
            file: linux/Dockerfile
            tag-suffix: -linux-arm64-8
          - platform: windows/amd64
#            os: windows-latest
            os: windows-2022
            base: ltsc2022
            file: windows/Dockerfile
            tag-suffix: -windows-amd64
    steps:
      - name: Set release version
        run: |
          echo "RELEASE_VERSION=$(echo '${{ github.event.inputs.version }}' | sed -e s/^v//)" >> $GITHUB_ENV
#          echo "RELEASE_VERSION=$(echo '${{ github.event.release.tag_name }}' | sed -e s/^v//)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker info
        run: docker info
      - name: Docker buildx inspect
        run: docker buildx inspect
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.file }}
          build-args: |
            BASE=${{ matrix.base }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: gesellix/echo-server:${{ env.RELEASE_VERSION }}${{ matrix.tag-suffix }}
...
